[package]
name = "mdbook-katex"
version = "0.1.5"
authors = ["Lucas Zanini <zanini.lcs@gmail.com>"]
edition = "2018"
description = "Mdbook preprocessor converting Katex equations to html."
license = "MIT"
readme = "README.md"

[dependencies]
katex = "0.2.4"
clap = "2.33.3"
mdbook = "0.4.4"
serde_json = "1.0.59"
toml = "0.5.7"
