[package]
name = "mdbook-katex"
version = "0.2.19"
authors = [
    "Lucas Zanini <zanini.lcs@gmail.com>",
    "Steven Hé (Sīchàng) <stevensichanghe@gmail.com>",
]
edition = "2021"
description = "mdBook preprocessor rendering LaTeX equations to HTML."
license = "MIT"
readme = "README.md"
repository = "https://github.com/lzanini/mdbook-katex"

[dependencies]
clap = { version = "4.0", features = ["cargo"] }
env_logger = { version = "0.10", optional = true }
log = { version = "0.4", optional = true }
mdbook = "0.4.23"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
reqwest = { version = "0.11", features = ["blocking"] }
regex = "1.7"
tokio = { version = "1.23", features = ["rt-multi-thread"] }

[target.'cfg(unix)'.dependencies]
katex = "0.4.5"

[target.'cfg(windows)'.dependencies]
katex = { version = "0.4.5", default-features = false, features = ["duktape"] }

[profile.release]
lto = true

[features]
log = ["dep:env_logger", "dep:log"]
