[package]
name = "mdbook-katex"
version = "0.2.19"
authors = [
    "Lucas Zanini <zanini.lcs@gmail.com>",
    "Steven Hé (Sīchàng) <stevensichanghe@gmail.com>",
]
edition = "2021"
description = "mdBook preprocessor rendering LaTeX equations to HTML."
license = "MIT"
readme = "README.md"
repository = "https://github.com/lzanini/mdbook-katex"

[dependencies]
clap = { version = "3.2.23", features = ["cargo"] }
mdbook = "0.4.23"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5.9"
reqwest = { version = "0.11", features = ["blocking"] }
regex = "1.7"

[target.'cfg(unix)'.dependencies]
katex = "0.4.5"

[target.'cfg(windows)'.dependencies]
katex = { version = "0.4.5", default-features = false, features = ["duktape"] }

[profile.release]
lto = true
