[package]
name = "mdbook-katex"
version = "0.2.24"
authors = [
    "Lucas Zanini <zanini.lcs@gmail.com>",
    "Steven Hé (Sīchàng) <stevensichanghe@gmail.com>",
]
edition = "2021"
description = "mdBook preprocessor rendering LaTeX equations to HTML."
license = "MIT"
readme = "README.md"
repository = "https://github.com/lzanini/mdbook-katex"

[dependencies]
clap = { version = "4.0", features = ["cargo"] }
mdbook = "0.4.25"
reqwest = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
regex = "1.7"
tokio = { version = "1.24", features = ["rt-multi-thread"] }

[target.'cfg(unix)'.dependencies]
katex = "0.4.5"

[target.'cfg(windows)'.dependencies]
katex = { version = "0.4.5", default-features = false, features = ["duktape"] }

[profile.release]
lto = true
