name: test-ci
on:
  push:
  pull_request:

jobs:
  test-ubuntu:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: Swatinem/rust-cache@v2

      - run: cargo test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2

      - run: cargo test

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - uses: Swatinem/rust-cache@v2

      - run: cargo test

  fmt-clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: check formatting
        run: cargo fmt -- --check

      - name: clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy

      - name: check Cargo.lock
        run: cargo update --locked
